<?php
$articles = Article::find();
if ($articles->count() > 0): ?>
<style>
    .container {
 width: 100%;
  margin: auto;
  height: auto;
  place-items: center;
  background-color: #7599c2;
}

.footer {
    margin-top: 0px;
}

.items {
  width: 85%;
  background: white;
 margin: auto;
 height: max-content;
 padding-top: 10px;
}
.items-head p{
  padding: 5px 20px;
  margin: 10px;
  color: #326899;
  font-weight: bold;
  font-size: 4vw;
}
hr {
    width: 35%;
    height: 3px;
    background-color: #7599c2;
    border-radius: 1px;
    border: 0;
    
  margin: 0px 30px;
  
}
.items-body {
  padding: 10px;
  margin: 10px;
  display: grid;
  grid-gap: 10px;
}
.items-body-content {
  padding: 10px;
  padding-right: 0px;
  display: grid;
  grid-template-columns: 10fr 1fr;
  // background-color: lightblue;
  font-size: 1.1em;
  grid-gap: 10px;
  border: 1px solid transparent;
  cursor: pointer;
  
}
.items-body-content i {
  align-self: center;
  font-size: 15px;
 
  font-weight: bold;
  animation: icon 1.5s infinite forwards;
}
@keyframes icon {
  0%,100%{
    transform: translate(0px);
  }
  50% {
    transform: translate(3px);
  }
}

</style>
<div class="container">
    <div class="items">
        <div class="items-head">
            <p>READ NEXT</p>
            <hr>
        </div>
        <div class="items-body">
            <?php foreach ($articles as $article): 
                if ($article_skip_id === $article->getId()): 
                    continue;
                endif; ?>
                <div class="items-body-content">
                    <span><a href="<?= $article->getLink() ?>"><?= $article->getTitle() ?></a></span>
                    <i class="fa fa-angle-right"></i>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>
