<section class="hero">
        <div class="hero-content">
            <h3>the fourth technical revolution</h3>
</div>

<a class="container-arrow scroll-to" >
  <span>
    <i class="fa fa-angle-down" aria-hidden="true"></i>  </span>
</a>

</section>
  

 <section id="section-2" class="section" >
        <h2 class="atitle">What is it?</h2>
        <p>Industry 4.0 is a technical revolution that embodies automation of production,
            the dissemination of Internet of things, analysis and processing of Big data,
            the use of neural networks and the creation of artificial intelligence.
            The purpose of this revolution is to unite all technologies into one self-regulating
            system that erases the boundaries of physical, digital and biological spheres.</p>
        <hr>
    </section>

    <section class="history">
        <div class="timeline-container" id="timeline-1">
  <div class="timeline-header">
    <h2 class="timeline-header__title">HISTORY</h2>
  </div>
  <div class="timeline">
    <div class="timeline-item" data-text="INDUSTRY 1.0">
      <div class="timeline__content"><img class="timeline__img" src="content/phototimeline1.jpg"/>
        <h2 class="timeline__content-title">18TH CENTURY</h2>
        <p class="timeline__content-desc">New scientific foundations of mathematics, astronomy, mechanics and medicine were laid. Construction and opening of railways began. The invention of the steam engine led to the large-scale development of industrial production.</p>
      </div>
    </div>
    <div class="timeline-item" data-text="INDUSTRY 2.0">
      <div class="timeline__content"><img class="timeline__img" src="content/phototimeline12.jpg"/>
        <h2 class="timeline__content-title">20TH CENTURY</h2>
        <p class="timeline__content-desc">The second technological revolution is known by the invention of the electric motor, telephone, aircraft, the transition to the use of oil, the launch mass production of cars, the spread of conveyors and internal combustion engines.</p>
      </div>
    </div>
    <div class="timeline-item" data-text="INDUSTRY 3.0">
      <div class="timeline__content"><img class="timeline__img" src="content/phototimeline2.jpg"/>
        <h2 class="timeline__content-title">1970S</h2>
        <p class="timeline__content-desc">The third industrial revolution is characterized by the emergence of nuclear energy, the creation of computers, discoveries in the field of biotechnology. This revolution has caused an era of high-level automation of production.</p>
      </div>
    </div>
    <div class="timeline-item" data-text="INDUSTRY 4.0">
      <div class="timeline__content"><img class="timeline__img" src="content/phototimeline4.jpg"/>
        <h2 class="timeline__content-title">TODAY</h2>
        <p class="timeline__content-desc">The start of using neural networks and 3D Printing, inventing of quantum computers and implementing of robotics in our everyday life.</p>
      </div>
    </div>
     </div>
</div>

    </section>


    <?= $this->partial('article\list_index') ?>
