<!DOCTYPE html>
<html lang="<?= $this->lang->getCurrent()->getId() ?>">
<head>
    <base href="<?= $this->url->path($this->url->get()) ?>">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Industry 4.0</title>
    <meta name="keywords" content="Industry 4.0, technical revolution, industrial revolution, internet of things, big data, cloud computing, cyberphysical systems, artificial intelligence, advanced robotics, Індустрія 4.0, технічна революція, промислова революція, великі дані">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="content/favicon.ico" type="image/x-icon">
    <link rel="stylesheet prefetch" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet prefetch" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" media="all" href="assets/css/frontend.css">
    <style>
    .button a {
        width: 17vw;
        padding: 1.2vw 4.8vw;
        text-align: center;
        color: white;
        border: solid 2px white;
        z-index: 1;
        text-decoration: none;
    }
    </style>
</head>
<body>
    <header>
        <?php $menus = Menu::find();
        if (count($menus) > 0): ?>
            <ul id="nav" class="menu menu-hover-lines">
                <?php foreach ($menus as $menu): ?>
                    <li <?php //class="active"?>><a class="js-anchor-link" href="<?= $menu->getUrl() ?>"><?= $menu->getTitle(); ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php
        // Current URI.
        $current_uri = $this->router->getRewriteUri();
        // If current URI does not containt lang code let's add current lang code.
        if (strpos($current_uri, '/' . $this->lang->getCurrent()->getId()) === FALSE):
            $current_uri .= $this->lang->getCurrent()->getId();
        endif;

        $current_uri = rtrim($current_uri, '/').'/';
        $langs = $this->lang->getAll();
        if (count($langs) > 1):
            foreach ($langs as $lang):
                if ($this->lang->getCurrent()->getId() === $lang->getId()):
                    continue;
                endif;?>
                <a href="<?= rtrim(str_replace('/'.$this->lang->getCurrent()->getId().'/', '/'.$lang->getId().'/', $current_uri), '/');?>"><div class="link"><?= $lang->getTitle() ?></div></a>
            <?php endforeach;
        endif; ?>
    </header>
    <?= $this->getContent(); ?>
    <footer class="footer">
            <h2><?= $this->translate->_('footer.about') ?></h2>
            <div class="icons">
                <a href="http://www.facebook.com/sharer.php?u=<?= $this->getDi()->get('url')->getBaseUri() ?>" rel="nofollow" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/intent/tweet?text=<?= $this->getDi()->get('url')->getBaseUri() ?>"><i class="fa fa-twitter"></i></a>
                <a href="https://plusone.google.com/_/+1/confirm?hl=ru&url=<?= $this->getDi()->get('url')->getBaseUri() ?>"><i class="fa fa-google-plus"></i></a>
                <a href="http://pinterest.com/pin/create/link/?url=<?= $this->getDi()->get('url')->getBaseUri() ?>"><i class="fa fa-pinterest"></i></a>
            </div>
            <h4><?= $this->translate->_('footer.copyright') ?></h4>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="assets/js/tindex.js"></script>
    <script>
    $(document).ready(function () {
        var jq_html = $("html");
        /**
         * Smooth scroll functionality for anchor links (animates the scroll
         * rather than a sudden jump in the page)
         */
        $(".js-anchor-link").click(function (e) {
            e.preventDefault();
            var jq_this = $(this);
            var href = jq_this.attr("href");
            var target = [];
            var i_anchor = href.indexOf("#");
            if (i_anchor > -1) {
                target = $(href.substring(i_anchor));
            }
            if (target.length){
                var scrollTo = target.offset().top;
                jq_html.animate({scrollTop: scrollTo+"px"}, 800);
            }
        });
    });
    </script>
</body>
</html>
