<?php
use Backend\Forms\AuthLoginForm as Form;
/**
 * View's variables:
 * @var Form $item_form
 */
?>

<?php if (isset($item_form) && $item_form instanceof Form): ?>

    <form class="form-horizontal col-md-6 col-xs-12 float-left m-0 p-0" accept-charset="UTF-8" role="form" method="post" action="<?= $this->url->get(['for' => 'backend/login']) ?>">
 <?php foreach ($item_form as $form_element):
            if ($form_element instanceof Phalcon\Forms\Element\Hidden):
                echo $form_element->render(['class' => 'form-control', 'required' => 'required']);
            else:
                $messages = $item_form->getMessagesFor($form_element->getName());
                ?><div class="form-group<?php if ($messages->count() > 0):?> has-error<?php endif; ?>">
                <?php /*<label class="control-label" for="<?= $form_element->getName() ?>"><?= $form_element->getLabel() ?></label>*/ ?>

                <?php
                echo $form_element->render(['class' => 'form-control', 'required' => 'required', 'placeholder' =>  $form_element->getLabel()]);
                if ($messages->count() > 0):
                    foreach ($messages as $message):
                        ?><span class="help-inline" for="<?= $form_element->getName() ?>"><i class="fa fa-exclamation-circle"></i>&nbsp;<?= $message->getMessage() ?></span><?php
                    endforeach;
                endif;
                ?>
                </div><?php
            endif;
        endforeach;
        ?>
        <div class="form-group">
            <button type="submit" class="btn btn-dark br0">Sign In</button>
        </div>
    </form>
<?php endif; ?>
