<!DOCTYPE html>
<html>
<head>
    <base href="<?= $this->url->path($this->url->get()) ?>">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Industry 4.0</title>
    <link rel="stylesheet" type="text/css" media="all" href="assets/css/backend.css">
</head>
<body>
    <header>
        <h1 class="pl-2">Admin panel</h1>
    </header>
    <div class="container-fluid">
        <div class="row">
            <?php if ($this->auth->isLoggedIn() === true): ?>
                <div class="col-auto" style="width: 300px;">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="<?= $this->url->get(['for' => 'backend/page/list']) ?>">Pages list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url->get(['for' => 'backend/article/list']) ?>">Articles</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url->get(['for' => 'backend/navigation/list']) ?>">Navigation</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url->get(['for' => 'backend/user/list']) ?>">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url->get(['for' => 'backend/logout']) ?>">Log out</a>
                        </li>
                    </ul>
                </div>
            <?php endif; ?>
            <div class="col">
                <?= $this->getContent(); ?>
            </div>
        </div>
    </div>
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.js"></script>
</body>
</html>
