<?php
$items = Page::find([
    'order' => 'name ASC',
]);
?>

<table class="table">
  <thead>
    <tr>
      <th scope="col" style="width: 3em;">#</th>
      <th scope="col">Name</th>
      <th scope="col" style="width: 3em;">Delete</th>
    </tr>
  </thead>

  <tbody>
  <?php
  $i_item = 0;
  ?>
  <?php foreach($items as $item): ?>
    <tr>
      <th scope="row"><?= ++$i_item ?></th>
      <td><a href="<?= $item->getLinkBackendEdit() ?>"><?= $item->getName() ?></a></td>
      <td><a class="btn btn-danger" href="<?= $item->getLinkBackendDelete() ?>"><i class="far fas fa-trash-alt"></i></a></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>


<a href="<?= $this->url->get(['for' => 'backend/page/add']) ?>">Add</a>
